In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/transactions.csv")

In [4]:
df.head()

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
0,4d3db980-46cd-4158-a812-dcb77055d0d2,2024-06-22 04:06:38,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,FAILED
1,099ee548-2fc1-4811-bf92-559c467ca792,2024-06-19 06:04:49,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,SUCCESS
2,d4c05732-6b1b-4bab-90b9-efe09d252b99,2024-06-04 04:56:09,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,SUCCESS
3,e8df92ee-8b04-4133-af5a-5f412180c8ab,2024-06-09 09:56:07,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,SUCCESS
4,e7d675d3-04f1-419c-a841-7a04662560b7,2024-06-25 08:38:19,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,SUCCESS

In [5]:
df.tail()

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
995,843d87b5-902e-4336-9438-aa76d74e13e4,2024-07-03 23:15:06,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,SUCCESS
996,2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,2024-06-15 15:42:57,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,FAILED
997,7c38e684-5968-432e-8acb-5bbe0f718fad,2024-06-18 17:27:37,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,FAILED
998,27624b55-fd6d-45ce-bbc5-0c2958d48865,2024-06-05 21:57:36,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,FAILED
999,b792bf64-2047-4435-aac1-27ee95b134d6,2024-06-21 15:52:40,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,SUCCESS

In [6]:
df.shape

(1000, 8)

In [7]:
df.columns

Index(['Transaction ID', 'Timestamp', 'Sender Name', 'Sender UPI ID',
       'Receiver Name', 'Receiver UPI ID', 'Amount (INR)', 'Status'],
      dtype='str')

In [8]:
df.isnull().sum()

Transaction ID     0
Timestamp          0
Sender Name        0
Sender UPI ID      0
Receiver Name      0
Receiver UPI ID    0
Amount (INR)       0
Status             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.describe()

       Amount (INR)
count   1000.000000
mean    4999.022930
std     2873.484534
min       28.520000
25%     2521.620000
50%     4951.435000
75%     7315.835000
max     9993.060000

In [11]:
df["Status"].value_counts()

Status
SUCCESS    502
FAILED     498
Name: count, dtype: int64